### ISSUE TITLE
云函数中执行报错

### ISSUE THREAD

**Issue by DaZiYuan** [TencentCloudBase/cloudbase-manager-node#12]
同样的代码，本地调试不会报错。上传到云函数就报错
```
    const CloudBase = require('@cloudbase/manager-node')
    const _app = new CloudBase({
        env: 'xxxx',//process.env.DB_ENV_ID,
        secretId: process.env.DB_SECRET_ID,
        secretKey: process.env.DB_SECRET_KEY,
    });

    let r = await _app.database.createCollectionIfNotExists('name');

```
报错
```
{ CloudBaseError: Environment  not found

    at envConfig.getEnvInfo.then.envInfo (/var/user/node_modules/crawler_common/node_modules/@cloudbase/manager-node/lib/environment.js:39:27)

    at process._tickCallback (internal/process/next_tick.js:68:7)

  name: 'CloudBaseError',

  message: 'Environment  not found',

  original: null,

  code: '',

  requestId: '',

  action: '' }

```

**Comment by Mrjing** [comment]
这个环境变量 process.env.DB_ENV_ID  ，是不是你自己本地注入了

**Comment by DaZiYuan** [comment]
我写死字符串，也是一样的错误

**Comment by DaZiYuan** [comment]
我打印了process.env.DB_ENV_ID，是有值的

**Comment by Mrjing** [comment]
const app = new CloudBase({
  secretId: 'Your SecretId',
  secretKey: 'Your SecretKey',
  envId: 'Your envId' // 云开发环境ID，可在腾讯云云开发控制台获取
})

**Comment by Mrjing** [comment]
const app = new CloudBase({
  secretId: 'Your SecretId',
  secretKey: 'Your SecretKey',
  envId: 'Your envId' // 云开发环境ID，可在腾讯云云开发控制台获取
})

这里初始化的时候env的指定是envId，这里和node-sdk有些区别，这里我们之后做下字段的兼容

**Comment by DaZiYuan** [comment]
改成envId后，任然报错
```
{ CloudBaseError: Environment mscoder-1dcc93 not found

    at envConfig.getEnvInfo.then.envInfo (/var/user/node_modules/crawler_common/node_modules/@cloudbase/manager-node/lib/environment.js:39:27)

    at process._tickCallback (internal/process/next_tick.js:68:7)

  name: 'CloudBaseError',

  message: 'Environment mscoder-1dcc93 not found',

  original: null,

  code: '',

  requestId: '',

  action: '' }
```

**Comment by DaZiYuan** [comment]
而且这个错误的命名在本机可以跑。

之前提过类似的问题......
https://github.com/TencentCloudBase/tcb-admin-node/issues/11

**Comment by DaZiYuan** [comment]
![image](https://user-images.githubusercontent.com/80653/98318427-8efabb80-2019-11eb-8bb5-58284e60cd81.png)
环境是有的

**Comment by DaZiYuan** [comment]
有个特点就是，我同使使用了tcb和 manager sdk，不知道会不会有影响
```
const tcb = require('@cloudbase/node-sdk');
const app = tcb.init({
    env: process.env.DB_ENV_ID,
    secretId: process.env.DB_SECRET_ID,
    secretKey: process.env.DB_SECRET_KEY,
});
const db = app.database();


 //主要拿来创建表
    const CloudBase = require('@cloudbase/manager-node')
    const _app = new CloudBase({
        envId: process.env.DB_ENV_ID,//'mscoder-1dcc93',
        secretId: process.env.DB_SECRET_ID,
        secretKey: process.env.DB_SECRET_KEY,
    });
```

**Comment by Mrjing** [comment]
同时使用应该是不会有影响的，这里会不会是使用的envid 不是当前 这个账号的呢

**Comment by DaZiYuan** [comment]
我用tcb读写数据，manager-node建表。都是从一个配置文件读出来的。现在的现象是不能建表，我手动建立集合可以正常写入数据
```
const app = tcb.init({
    env: process.env.DB_ENV_ID,
    secretId: process.env.DB_SECRET_ID,
    secretKey: process.env.DB_SECRET_KEY,
});
```
```
    const _app = new CloudBase({
        envId: process.env.DB_ENV_ID,//'mscoder-1dcc93',
        secretId: process.env.DB_SECRET_ID,
        secretKey: process.env.DB_SECRET_KEY,
    });
```

**Comment by Mrjing** [comment]
可以提供下你的这个腾讯云账户的uin信息么，我查下后台日志

**Comment by DaZiYuan** [comment]
100000617780

**Comment by Mrjing** [comment]
方便加微信沟通吗，有些问题可以详细沟通下，我的微信号是kk33883386

**Comment by DaZiYuan** [comment]
添加区域后正常了
```
    const _app = new CloudBase({
        envId: process.env.DB_ENV_ID,//'mscoder-1dcc93',
        secretId: process.env.DB_SECRET_ID,
        secretKey: process.env.DB_SECRET_KEY,
        region: "ap-shanghai"
    });
```
